version: "3.9"
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: mangorest
    volumes:
      - ./tests/db-init.js:/docker-entrypoint-initdb.d/db-init.js
    ports:
      - "27017:27017"
