name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-root

      - name: Install poetry
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==1.1.11

      - name: Configure poetry
        run: |
          python -m poetry config virtualenvs.create false

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: python -m poetry install

      - name: Start containers
        run: docker-compose -f compose-mongodb.yml up -d --build

      - name: Lint
        run: python -m poetry run bash scripts/lint-check.sh

      - name: Test
        run: python -m poetry run pytest
        env:
          FLASK_ENV: testing
          FLASK_APP: mangorest:app
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          DATABASE: ${{ secrets.DATABASE }}
          COLLECTIONS: ${{ secrets.COLLECTIONS }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

      - name: Stop containers
        run: docker-compose -f compose-mongodb.yml down
